import { createRequire, enableCompileCache } from "node:module";
import type { MessagePort } from "node:worker_threads";
import { parentPort, workerData } from "node:worker_threads";
import type { Client, Pool } from "pg";

// db:check worker (TMU-OPS-005). Owns the network-heavy scratch-database lifecycle — connect to
// the source database, CREATE the scratch database, apply the migrations, then drop the scratch
// database when the main thread posts "finish" — so the main thread can load drizzle-kit (a
// 2.8 MB bundle that costs over a second of pure CPU) in parallel. The frozen Vitest timeout
// for the live db:check tests is 5 s, which a single-threaded sequence cannot beat reliably.
//
// The scratch name is generated by the main thread and is always a safe unquoted identifier
// (`tmu_check_<millis>_<hex>`), so it is interpolated directly. The source URL is used verbatim:
// no sslmode rewriting (CI is plaintext, the hosted instance carries `?sslmode=require`), and
// neither the URL nor its contents are ever logged.

interface CheckWorkerConfig {
  sourceUrl: string;
  scratchName: string;
  migrationsDir: string;
}

interface WorkerMessage {
  phase: string;
  message?: string;
}

const require = createRequire(import.meta.url);

/** FIFO queue of messages from the main thread; messages may arrive before or after a wait. */
class MainInbox {
  private readonly pending: WorkerMessage[] = [];
  private readonly waiters: Array<(message: WorkerMessage) => void> = [];

  constructor(port: MessagePort) {
    port.on("message", (message: WorkerMessage) => this.push(message));
  }

  private push(message: WorkerMessage): void {
    const waiter = this.waiters.shift();
    if (waiter) waiter(message);
    else this.pending.push(message);
  }

  next(): Promise<WorkerMessage> {
    const buffered = this.pending.shift();
    if (buffered) return Promise.resolve(buffered);
    return new Promise((resolve) => this.waiters.push(resolve));
  }
}

function post(port: MessagePort, message: WorkerMessage): void {
  try {
    port.postMessage(message);
  } catch {
    // Main thread is gone; there is nobody left to report to.
  }
}

async function run(): Promise<void> {
  const port = parentPort;
  if (!port) throw new Error("db:check worker requires a parent port");
  const config = workerData as CheckWorkerConfig;
  const inbox = new MainInbox(port); // listen before any await so "finish" is never lost

  let admin: Client | undefined;
  let pool: Pool | undefined;
  try {
    enableCompileCache();
    const pg = require("pg") as typeof import("pg");
    const drizzleModule =
      require("drizzle-orm/node-postgres") as typeof import("drizzle-orm/node-postgres");
    const migratorModule =
      require("drizzle-orm/node-postgres/migrator") as typeof import("drizzle-orm/node-postgres/migrator");

    admin = new pg.Client({ connectionString: config.sourceUrl });
    await admin.connect();
    await admin.query(`CREATE DATABASE ${config.scratchName}`);
    post(port, { phase: "scratch-ready" });

    const scratchUrl = new URL(config.sourceUrl);
    scratchUrl.pathname = `/${config.scratchName}`;
    pool = new pg.Pool({ connectionString: scratchUrl.toString(), max: 1 });
    await migratorModule.migrate(drizzleModule.drizzle(pool), {
      migrationsFolder: config.migrationsDir,
    });
    post(port, { phase: "migrate-done" });
  } catch (cause) {
    post(port, {
      phase: "failed",
      message: cause instanceof Error ? cause.message : String(cause),
    });
  }

  // The main thread always posts "finish" from its finally block: drift, failure or not.
  await inbox.next();

  if (pool) {
    await pool.end().catch(() => undefined);
  }
  if (admin) {
    try {
      await admin.query(`DROP DATABASE IF EXISTS ${config.scratchName} WITH (FORCE)`);
    } catch {
      // Best effort: a leftover scratch database must never fail the check.
    }
    await admin.end().catch(() => undefined);
  }
  post(port, { phase: "done" });
}

void run().catch(() => undefined); // an uncaught failure surfaces as "exit" on the main thread
