// Contract artefact generator (TMU-OPS-004; BE-02 "Conventions baked into the generator").
// Pure and deterministic: the same version produces the same bytes (no clocks, no randomness,
// no I/O). `scripts/build.ts` is the only writer of these four derived artefacts; CI rebuilds
// them and fails on drift (docs/04-contracts/README.md governance).
import { zodToJsonSchema } from "zod-to-json-schema";
import { stringify } from "yaml";
import type { z } from "zod";
import { ErrorEnvelope } from "./common.ts";
import { ERROR_STATUS } from "./errors.ts";
import { examples } from "./examples.ts";
import { registry } from "./registry.ts";
import type { RouteDef } from "./registry.ts";

export type GeneratedFile = { path: string; content: string };

const OPENAPI_PATH = "docs/04-contracts/backend/BE-02-openapi.yaml";
const TYPES_PATH = "packages/contracts/generated/types.ts";
const CLIENT_PATH = "packages/contracts/generated/client.ts";
const MSW_PATH = "packages/contracts/generated/msw-handlers.ts";

const ERROR_ENVELOPE_NAME = "ErrorEnvelope";
const ERROR_ENVELOPE_REF = "#/components/schemas/ErrorEnvelope";

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

const isJsonObject = (value: unknown): value is JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value);

// The pinned zod-to-json-schema names the OpenAPI-3.0-compatible target "openApi3" (there is no
// "openapi-3.0" target; an unknown string is silently ignored). It emits `enum` for literals.
const toJsonSchema = (schema: z.ZodTypeAny): JsonObject =>
  zodToJsonSchema(schema, {
    target: "openApi3",
    $refStrategy: "none",
  }) as unknown as JsonObject;

const jsonLiteral = (value: unknown): string => JSON.stringify(value) ?? "null";

const yamlBanner = (version: string): string =>
  [
    "# @generated by pnpm contracts:build from packages/contracts — do not edit",
    `# contract version: ${version}`,
    "",
  ].join("\n");

const tsBanner = (version: string): string =>
  [
    "// @generated by pnpm contracts:build from packages/contracts — do not edit",
    `// contract version: ${version}`,
  ].join("\n");

type ResponseComponent = { name: string; schema: JsonObject };

type OpenApiModel = {
  doc: JsonObject;
  responseComponents: readonly ResponseComponent[];
  nameByRoute: ReadonlyMap<string, string>;
};

const errorStatusesOf = (route: RouteDef): string[] => [
  ...new Set(route.errors.map((code) => String(ERROR_STATUS[code]))),
];

const ensureResponseComponent = (
  route: RouteDef,
  componentBySchema: Map<z.ZodTypeAny, ResponseComponent>,
  components: ResponseComponent[],
): ResponseComponent => {
  const existing = componentBySchema.get(route.response);
  if (existing !== undefined) return existing;
  const component: ResponseComponent = {
    name: `${route.id}Response`,
    schema: toJsonSchema(route.response),
  };
  componentBySchema.set(route.response, component);
  components.push(component);
  return component;
};

const buildOpenApiModel = (version: string): OpenApiModel => {
  const componentBySchema = new Map<z.ZodTypeAny, ResponseComponent>();
  const responseComponents: ResponseComponent[] = [];
  const nameByRoute = new Map<string, string>();
  const paths: JsonObject = {};

  for (const route of registry) {
    const component = ensureResponseComponent(route, componentBySchema, responseComponents);
    nameByRoute.set(route.id, component.name);

    const responses: JsonObject = {
      "200": {
        headers: { "X-Request-Id": { schema: { type: "string" } } },
        content: {
          "application/json": { schema: { $ref: `#/components/schemas/${component.name}` } },
        },
      },
    };

    for (const code of route.errors) {
      const status = String(ERROR_STATUS[code]);
      const existing = responses[status];
      if (isJsonObject(existing) && Array.isArray(existing["x-error-codes"])) {
        existing["x-error-codes"].push(code);
        continue;
      }
      responses[status] = {
        headers: { "X-Request-Id": { schema: { type: "string" } } },
        content: { "application/json": { schema: { $ref: ERROR_ENVELOPE_REF } } },
        "x-error-codes": [code],
      };
    }

    const existingPath = paths[route.path];
    const pathItem: JsonObject = isJsonObject(existingPath) ? existingPath : {};
    pathItem[route.method] = {
      operationId: route.id,
      security: route.auth === "public" ? [] : [{ cookieAuth: [] }],
      responses,
    };
    paths[route.path] = pathItem;
  }

  const schemas: JsonObject = { [ERROR_ENVELOPE_NAME]: toJsonSchema(ErrorEnvelope) };
  for (const component of responseComponents) {
    schemas[component.name] = component.schema;
  }

  return {
    doc: {
      openapi: "3.1.0",
      info: { title: "TemuUNAIR API", version },
      paths,
      components: {
        securitySchemes: {
          cookieAuth: { type: "apiKey", in: "cookie", name: "__Secure-temuunair.session" },
        },
        schemas,
      },
    },
    responseComponents,
    nameByRoute,
  };
};

const requireComponentName = (model: OpenApiModel, routeId: string): string => {
  const name = model.nameByRoute.get(routeId);
  if (name === undefined) {
    throw new Error(`No response component registered for ${routeId}`);
  }
  return name;
};

const requiredKeysOf = (schema: JsonObject): ReadonlySet<string> => {
  const required = schema["required"];
  const keys = Array.isArray(required)
    ? required.filter((key): key is string => typeof key === "string")
    : [];
  return new Set(keys);
};

const primitiveTypeOf = (type: unknown): string => {
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "unknown";
  }
};

const tsTypeOf = (schema: JsonObject): string => {
  if ("const" in schema) return jsonLiteral(schema["const"]);
  const enumValues = schema["enum"];
  if (Array.isArray(enumValues)) {
    return enumValues.map((value) => jsonLiteral(value)).join(" | ");
  }
  const type = schema["type"];
  if (Array.isArray(type)) {
    return type.map((entry) => primitiveTypeOf(entry)).join(" | ");
  }
  if (type === "array") {
    const items = schema["items"];
    return `Array<${isJsonObject(items) ? tsTypeOf(items) : "unknown"}>`;
  }
  if (type === "object") {
    const properties = schema["properties"];
    if (!isJsonObject(properties)) return "Record<string, unknown>";
    const required = requiredKeysOf(schema);
    const members = Object.entries(properties).map(([key, value]) => {
      const optional = required.has(key) ? "" : "?";
      const memberType = isJsonObject(value) ? tsTypeOf(value) : "unknown";
      return `${jsonLiteral(key)}${optional}: ${memberType};`;
    });
    return members.length > 0 ? `{ ${members.join(" ")} }` : "Record<string, unknown>";
  }
  return primitiveTypeOf(type);
};

const buildOpenApiFile = (version: string, doc: JsonObject): string =>
  `${yamlBanner(version)}${stringify(doc, { lineWidth: 0 })}`;

const buildTypesFile = (version: string, model: OpenApiModel): string => {
  const lines: string[] = [tsBanner(version), ""];

  lines.push("export interface paths {");
  for (const route of registry) {
    lines.push(`  ${jsonLiteral(route.path)}: {`);
    lines.push(`    ${route.method}: operations[${jsonLiteral(route.id)}];`);
    lines.push("  };");
  }
  lines.push("}", "");

  lines.push("export interface components {");
  lines.push("  schemas: {");
  lines.push(`    ${ERROR_ENVELOPE_NAME}: ${tsTypeOf(toJsonSchema(ErrorEnvelope))};`);
  for (const component of model.responseComponents) {
    lines.push(`    ${jsonLiteral(component.name)}: ${tsTypeOf(component.schema)};`);
  }
  lines.push("  };");
  lines.push("  securitySchemes: {");
  lines.push(
    '    cookieAuth: { type: "apiKey"; in: "cookie"; name: "__Secure-temuunair.session" };',
  );
  lines.push("  };");
  lines.push("}", "");

  lines.push("export interface operations {");
  for (const route of registry) {
    const name = requireComponentName(model, route.id);
    lines.push(`  ${jsonLiteral(route.id)}: {`);
    lines.push("    responses: {");
    lines.push(
      `      200: { content: { "application/json": components["schemas"][${jsonLiteral(name)}] } };`,
    );
    for (const status of errorStatusesOf(route)) {
      lines.push(
        `      ${status}: { content: { "application/json": components["schemas"]["${ERROR_ENVELOPE_NAME}"] } };`,
      );
    }
    lines.push("    };");
    lines.push("  };");
  }
  lines.push("}", "");

  return lines.join("\n");
};

const buildClientFile = (version: string): string =>
  [
    tsBanner(version),
    "",
    'import createClient from "openapi-fetch";',
    'import type { paths } from "./types.ts";',
    "",
    'export const api = createClient<paths>({ baseUrl: "" });',
    "",
  ].join("\n");

const buildMswFile = (version: string): string => {
  const lines = [
    tsBanner(version),
    "",
    'import { http, HttpResponse, type HttpHandler } from "msw";',
    "",
    "export const mswHandlers: HttpHandler[] = [",
  ];
  for (const route of registry) {
    const example = examples[route.id];
    if (example === undefined) {
      throw new Error(`examples is missing an entry for ${route.id}`);
    }
    lines.push(
      `  http.${route.method}("*${route.path}", () => HttpResponse.json(${jsonLiteral(example)})),`,
    );
  }
  lines.push("];", "");
  return lines.join("\n");
};

export function generateAll(version: string): GeneratedFile[] {
  const model = buildOpenApiModel(version);
  return [
    { path: OPENAPI_PATH, content: buildOpenApiFile(version, model.doc) },
    { path: TYPES_PATH, content: buildTypesFile(version, model) },
    { path: CLIENT_PATH, content: buildClientFile(version) },
    { path: MSW_PATH, content: buildMswFile(version) },
  ];
}
