// Route registry: the single source of truth for API ids, auth, schemas and error codes
// (docs/04-contracts/README.md; BE-02). The generator derives every artefact from this list.
// The minimal M0 set is frozen by TMU-OPS-004; the full catalogue lands in TMU-CTR-001..005.
import { z } from "zod";
import {
  AccountDeletionResponse,
  ActionStatusResponse,
  CampusMeta,
  CategoryMeta,
  Challenge,
  ChatMessage,
  ChatMessageCreate,
  ChatReadReceiptRequest,
  ChatStreamEvent,
  ClaimCancelRequest,
  ClaimCreate,
  ClaimDecisionRequest,
  ClaimDisputeRequest,
  ClaimRejectRequest,
  ClaimView,
  DropPointMeta,
  HandoverPlanRequest,
  HealthResponse,
  LocationMeta,
  MatchView,
  Me,
  MeUpdate,
  NotificationPrefs,
  paged,
  ReadyResponse,
  RematchResponse,
  ReportCancelRequest,
  ReportCreate,
  ReportFlagRequest,
  ReportFlagResponse,
  ReportOwnerView,
  ReportPublic,
  ReportUpdate,
  SearchHit,
  SearchRequest,
  UploadInitRequest,
  UploadInitResponse,
  UploadState,
} from "./common.ts";
import type { ErrorCode } from "./errors.ts";

export type Auth = "public" | "user" | "owner" | "moderator" | "admin";

export type RouteDef = {
  id: string;
  method: "get" | "post" | "put" | "patch" | "delete";
  path: string;
  auth: Auth;
  request: z.ZodTypeAny | null;
  response: z.ZodTypeAny;
  errors: ErrorCode[];
  rateLimit?: string;
  deprecated?: boolean;
};

export type ApiId = string;

export const registry: readonly RouteDef[] = [
  {
    id: "API-SYS-01",
    method: "get",
    path: "/healthz",
    auth: "public",
    request: null,
    response: HealthResponse,
    errors: [],
  },
  {
    id: "API-SYS-02",
    method: "get",
    path: "/readyz",
    auth: "public",
    request: null,
    response: ReadyResponse,
    errors: [],
  },
  {
    id: "API-META-01",
    method: "get",
    path: "/api/v1/meta/categories",
    auth: "user",
    request: null,
    response: z.array(CategoryMeta),
    errors: [],
  },
  {
    id: "API-META-02",
    method: "get",
    path: "/api/v1/meta/campuses",
    auth: "user",
    request: null,
    response: z.array(CampusMeta),
    errors: [],
  },
  {
    id: "API-META-03",
    method: "get",
    path: "/api/v1/meta/locations",
    auth: "user",
    request: null,
    response: z.array(LocationMeta),
    errors: ["VALIDATION_FAILED"],
  },
  {
    id: "API-META-04",
    method: "get",
    path: "/api/v1/meta/drop-points",
    auth: "user",
    request: null,
    response: z.array(DropPointMeta),
    errors: [],
  },
  {
    id: "API-ME-01",
    method: "get",
    path: "/api/v1/me",
    auth: "user",
    request: null,
    response: Me,
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-ME-02",
    method: "patch",
    path: "/api/v1/me",
    auth: "user",
    request: MeUpdate,
    response: Me,
    errors: ["AUTH_REQUIRED", "VALIDATION_FAILED"],
  },
  {
    id: "API-ME-03",
    method: "delete",
    path: "/api/v1/me",
    auth: "user",
    request: null,
    response: AccountDeletionResponse,
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-ME-04",
    method: "get",
    path: "/api/v1/me/notification-preferences",
    auth: "user",
    request: null,
    response: NotificationPrefs,
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-ME-05",
    method: "put",
    path: "/api/v1/me/notification-preferences",
    auth: "user",
    request: NotificationPrefs,
    response: NotificationPrefs,
    errors: ["AUTH_REQUIRED", "VALIDATION_FAILED"],
  },
  {
    id: "API-UPL-01",
    method: "post",
    path: "/api/v1/uploads",
    auth: "user",
    request: UploadInitRequest,
    response: UploadInitResponse,
    errors: ["AUTH_REQUIRED", "UPLOAD_INVALID_TYPE", "UPLOAD_TOO_LARGE", "RATE_LIMITED"],
  },
  {
    id: "API-UPL-02",
    method: "post",
    path: "/api/v1/uploads/{id}/complete",
    auth: "owner",
    request: null,
    response: UploadState,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "UPLOAD_INVALID_TYPE"],
  },
  {
    id: "API-UPL-03",
    method: "get",
    path: "/api/v1/uploads/{id}",
    auth: "owner",
    request: null,
    response: UploadState,
    errors: ["AUTH_REQUIRED", "NOT_FOUND"],
  },
  {
    id: "API-REP-01",
    method: "post",
    path: "/api/v1/reports",
    auth: "user",
    request: ReportCreate,
    response: ReportOwnerView,
    errors: ["AUTH_REQUIRED", "VALIDATION_FAILED", "RATE_LIMITED", "UPLOAD_LIMIT_REACHED"],
  },
  {
    id: "API-REP-02",
    method: "get",
    path: "/api/v1/reports",
    auth: "user",
    request: null,
    response: paged(ReportPublic),
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-REP-03",
    method: "get",
    path: "/api/v1/reports/mine",
    auth: "user",
    request: null,
    response: paged(ReportOwnerView),
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-REP-04",
    method: "get",
    path: "/api/v1/reports/{id}",
    auth: "user",
    request: null,
    response: ReportOwnerView,
    errors: ["AUTH_REQUIRED", "NOT_FOUND"],
  },
  {
    id: "API-REP-05",
    method: "patch",
    path: "/api/v1/reports/{id}",
    auth: "owner",
    request: ReportUpdate,
    response: ReportOwnerView,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "CONFLICT_STATE", "FORBIDDEN", "VALIDATION_FAILED"],
  },
  {
    id: "API-REP-06",
    method: "post",
    path: "/api/v1/reports/{id}/cancel",
    auth: "owner",
    request: ReportCancelRequest,
    response: ReportOwnerView,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "CONFLICT_STATE"],
  },
  {
    id: "API-REP-07",
    method: "post",
    path: "/api/v1/reports/{id}/renew",
    auth: "owner",
    request: null,
    response: ReportOwnerView,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "CONFLICT_STATE"],
  },
  {
    id: "API-REP-08",
    method: "post",
    path: "/api/v1/reports/{id}/flag",
    auth: "user",
    request: ReportFlagRequest,
    response: ReportFlagResponse,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "RATE_LIMITED", "VALIDATION_FAILED"],
  },
  {
    id: "API-SRC-01",
    method: "post",
    path: "/api/v1/search",
    auth: "user",
    request: SearchRequest,
    response: paged(SearchHit),
    errors: ["AUTH_REQUIRED", "VALIDATION_FAILED"],
  },
  {
    id: "API-MAT-01",
    method: "get",
    path: "/api/v1/reports/{id}/matches",
    auth: "owner",
    request: null,
    response: z.array(MatchView),
    errors: ["AUTH_REQUIRED", "FORBIDDEN", "NOT_FOUND"],
  },
  {
    id: "API-MAT-02",
    method: "post",
    path: "/api/v1/matches/{id}/dismiss",
    auth: "user",
    request: null,
    response: MatchView,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "CONFLICT_STATE"],
  },
  {
    id: "API-MAT-03",
    method: "post",
    path: "/api/v1/matches/{id}/invite",
    auth: "user",
    request: null,
    response: ActionStatusResponse,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "RATE_LIMITED"],
  },
  {
    id: "API-MAT-04",
    method: "post",
    path: "/api/v1/reports/{id}/rematch",
    auth: "owner",
    request: null,
    response: RematchResponse,
    errors: ["AUTH_REQUIRED", "NOT_FOUND", "RATE_LIMITED"],
  },
  {
    id: "API-CLM-01",
    method: "get",
    path: "/api/v1/reports/{id}/challenge",
    auth: "user",
    request: null,
    response: Challenge,
    errors: ["AUTH_REQUIRED", "REPORT_NOT_CLAIMABLE", "SELF_CLAIM_NOT_ALLOWED"],
  },
  {
    id: "API-CLM-02",
    method: "post",
    path: "/api/v1/claims",
    auth: "user",
    request: ClaimCreate,
    response: ClaimView,
    errors: [
      "AUTH_REQUIRED",
      "CLAIM_ALREADY_ACTIVE",
      "CLAIM_LIMIT_EXCEEDED",
      "REPORT_NOT_CLAIMABLE",
      "VALIDATION_FAILED",
    ],
  },
  {
    id: "API-CLM-03",
    method: "get",
    path: "/api/v1/claims",
    auth: "user",
    request: null,
    response: paged(ClaimView),
    errors: ["AUTH_REQUIRED"],
  },
  {
    id: "API-CLM-04",
    method: "get",
    path: "/api/v1/claims/{id}",
    auth: "user",
    request: null,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "FORBIDDEN", "NOT_FOUND"],
  },
  {
    id: "API-CLM-05",
    method: "post",
    path: "/api/v1/claims/{id}/approve",
    auth: "owner",
    request: ClaimDecisionRequest,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN"],
  },
  {
    id: "API-CLM-06",
    method: "post",
    path: "/api/v1/claims/{id}/reject",
    auth: "owner",
    request: ClaimRejectRequest,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN", "VALIDATION_FAILED"],
  },
  {
    id: "API-CLM-07",
    method: "put",
    path: "/api/v1/claims/{id}/handover-plan",
    auth: "user",
    request: HandoverPlanRequest,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN", "VALIDATION_FAILED"],
  },
  {
    id: "API-CLM-08",
    method: "post",
    path: "/api/v1/claims/{id}/confirm-handover",
    auth: "user",
    request: null,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN"],
  },
  {
    id: "API-CLM-09",
    method: "post",
    path: "/api/v1/claims/{id}/cancel",
    auth: "user",
    request: ClaimCancelRequest,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN"],
  },
  {
    id: "API-CLM-10",
    method: "post",
    path: "/api/v1/claims/{id}/dispute",
    auth: "user",
    request: ClaimDisputeRequest,
    response: ClaimView,
    errors: ["AUTH_REQUIRED", "CONFLICT_STATE", "FORBIDDEN", "VALIDATION_FAILED"],
  },
  {
    id: "API-CHT-01",
    method: "get",
    path: "/api/v1/claims/{id}/messages",
    auth: "user",
    request: null,
    response: paged(ChatMessage),
    errors: ["AUTH_REQUIRED", "FORBIDDEN", "NOT_FOUND"],
  },
  {
    id: "API-CHT-02",
    method: "post",
    path: "/api/v1/claims/{id}/messages",
    auth: "user",
    request: ChatMessageCreate,
    response: ChatMessage,
    errors: ["AUTH_REQUIRED", "RATE_LIMITED", "CONFLICT_STATE", "VALIDATION_FAILED"],
  },
  {
    id: "API-CHT-03",
    method: "get",
    path: "/api/v1/claims/{id}/stream",
    auth: "user",
    request: null,
    response: ChatStreamEvent,
    errors: ["AUTH_REQUIRED", "FORBIDDEN"],
  },
  {
    id: "API-CHT-04",
    method: "post",
    path: "/api/v1/claims/{id}/messages/read",
    auth: "user",
    request: ChatReadReceiptRequest,
    response: ActionStatusResponse,
    errors: ["AUTH_REQUIRED", "FORBIDDEN"],
  },
];

export const registryById = new Map(registry.map((route) => [route.id, route]));
