#!/usr/bin/env node
// Generates docs/08-project/backlog.md and docs/08-project/status.md from task front-matter.
// Never hand-edit the generated files (Blueprint §4.9).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const TASKS_DIR = "docs/08-project/tasks";

function parseFrontMatter(file) {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$/);
    if (!kv) continue;
    let [, key, value] = kv;
    value = value.replace(/\s+#.*$/, "").trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      fm[key] = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      fm[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return fm;
}

let files = [];
try {
  files = readdirSync(TASKS_DIR).filter((f) => f.endsWith(".md"));
} catch {
  // No tasks directory yet (pre-M0); the loop below simply produces an empty index.
}
const tasks = files
  .map((f) => {
    const fm = parseFrontMatter(join(TASKS_DIR, f));
    return fm && fm.id ? { ...fm, file: f } : null;
  })
  .filter(Boolean)
  .sort((a, b) => (a.milestone ?? "").localeCompare(b.milestone ?? "") || a.id.localeCompare(b.id));

const milestoneOrder = [...new Set(tasks.map((t) => t.milestone ?? "—"))];
const statuses = ["TODO", "IN_PROGRESS", "BLOCKED", "REVIEW", "DONE", "CANCELLED"];

let backlog = `<!-- GENERATED by scripts/backlog-index.mjs — do not edit by hand -->\n# Backlog index\n\n| ID | Milestone | Lane | Status | Priority | Title | Deps |\n|---|---|---|---|---|---|---|\n`;
for (const t of tasks) {
  backlog += `| [${t.id}](tasks/${t.file}) | ${t.milestone ?? ""} | ${t.lane ?? ""} | ${t.status ?? ""} | ${t.priority ?? ""} | ${t.title ?? ""} | ${(t.deps ?? []).join(", ")} |\n`;
}
writeFileSync("docs/08-project/backlog.md", backlog);

let status = `<!-- GENERATED by scripts/backlog-index.mjs — do not edit by hand -->\n# Status dashboard\n\n`;
for (const ms of milestoneOrder) {
  const msTasks = tasks.filter((t) => (t.milestone ?? "—") === ms);
  const counts = statuses
    .map((s) => `${s}: ${msTasks.filter((t) => t.status === s).length}`)
    .join(" · ");
  const pct = msTasks.length
    ? Math.round((msTasks.filter((t) => t.status === "DONE").length / msTasks.length) * 100)
    : 0;
  status += `## ${ms} — ${pct}%\n\n${counts}\n\n`;
  for (const t of msTasks)
    status += `- [${t.status === "DONE" ? "x" : " "}] ${t.id} — ${t.title ?? ""}\n`;
  status += "\n";
}
writeFileSync("docs/08-project/status.md", status);

console.log(`Wrote backlog.md (${tasks.length} tasks) and status.md`);
